language: python
python:
  - "2.7"
  - "3.6"
  - "pypy"
install:
  - "pip install -r tests/requirements.txt"
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "python setup.py develop"
script:
    python setup.py test
after_success:
    coveralls
